# Generated by Django 6.0.3 on 2026-04-14 13:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('customer_type', models.CharField(choices=[('trial', '试用客户'), ('self_develop', '自开发客户'), ('operations', '售后运维客户')], max_length=20, verbose_name='客户类型')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('lost', '流失')], max_length=20, verbose_name='当前状态')),
                ('contact_person', models.CharField(max_length=100, verbose_name='负责人')),
                ('opportunity_number', models.CharField(blank=True, max_length=100, verbose_name='商机编号')),
                ('customer_level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='客户级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户列表',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('deployment_environment', models.CharField(choices=[('test', '测试'), ('prod', '生产')], max_length=20, verbose_name='部署环境')),
                ('status', models.CharField(choices=[('normal', '正常'), ('error', '异常')], default='normal', max_length=20, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '流程列表',
                'verbose_name_plural': '流程列表',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('activation_key', models.CharField(blank=True, max_length=100, verbose_name='激活码')),
                ('key_expires', models.DateTimeField(blank=True, null=True, verbose_name='激活码过期时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTypeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_type', models.CharField(choices=[('trial', '试用客户'), ('self_develop', '自开发客户'), ('operations', '售后运维客户')], max_length=20, verbose_name='原类型')),
                ('new_type', models.CharField(choices=[('trial', '试用客户'), ('self_develop', '自开发客户'), ('operations', '售后运维客户')], max_length=20, verbose_name='新类型')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '客户类型变更日志',
                'verbose_name_plural': '客户类型变更日志',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='操作')),
                ('object_type', models.CharField(max_length=100, verbose_name='操作对象类型')),
                ('object_id', models.IntegerField(null=True, verbose_name='操作对象ID')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('details', models.TextField(blank=True, verbose_name='操作详情')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='问题标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('screenshot', models.FileField(blank=True, upload_to='image', verbose_name='问题截图')),
                ('occurrence_time', models.DateTimeField(blank=True, null=True, verbose_name='出现时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('problem_reason', models.TextField(blank=True, verbose_name='问题原因')),
                ('reason_type', models.CharField(blank=True, choices=[('bug', '缺陷bug'), ('env', '客户环境问题'), ('process', '流程问题'), ('consult', '客户咨询')], max_length=20, verbose_name='原因分类')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('solve_time', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('man_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='人天')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer', verbose_name='客户')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('related_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.process', verbose_name='关联流程')),
            ],
            options={
                'verbose_name': '问题记录',
                'verbose_name_plural': '问题记录',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('contract_start_date', models.DateField(verbose_name='合同开始时间')),
                ('contract_end_date', models.DateField(verbose_name='合同结束时间')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('ended', '结束')], default='active', max_length=20, verbose_name='项目状态')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer', verbose_name='客户')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
                ('technical_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_manager', to=settings.AUTH_USER_MODEL, verbose_name='技术负责人')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_type', models.CharField(max_length=50, verbose_name='类型')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
            },
        ),
        migrations.CreateModel(
            name='TrialCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_start_time', models.DateTimeField(verbose_name='试用开始时间')),
                ('trial_end_time', models.DateTimeField(verbose_name='试用到期时间')),
                ('conversion_status', models.BooleanField(default=False, verbose_name='转化状态')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '试用客户信息',
                'verbose_name_plural': '试用客户信息',
            },
        ),
    ]
