# Generated by Django 6.0.1 on 2026-03-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        # 修复 CustomerTypeChangeLog 表的外键约束
        migrations.AlterField(
            model_name='customertypechangelog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customuser', verbose_name='操作人'),
        ),
        # 修复 OperationLog 表的外键约束
        migrations.AlterField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customuser', verbose_name='操作人'),
        ),
        # 修复 Problem 表的外键约束
        migrations.AlterField(
            model_name='problem',
            name='handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customuser', verbose_name='处理人'),
        ),
        # 修复 Project 表的外键约束
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='service.customuser', verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technical_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_manager', to='service.customuser', verbose_name='技术负责人'),
        ),
        # 修复 File 表的外键约束
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customuser', verbose_name='上传人'),
        ),
    ]
