# Generated by Django 6.0.3 on 2026-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='客户id'),
        ),
    ]
