# Generated by Django 6.0.3 on 2026-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='客户id'),
        ),
    ]
