# Generated by Django 6.0.1 on 2026-03-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20260324_1141'),
    ]

    operations = [
        # 修复 CustomerTypeChangeLog 表的外键列类型
        migrations.RunSQL(
            'ALTER TABLE service_customertypechangelog MODIFY COLUMN operator_id BIGINT NULL',
            reverse_sql='ALTER TABLE service_customertypechangelog MODIFY COLUMN operator_id INT NULL'
        ),
        # 修复 OperationLog 表的外键列类型
        migrations.RunSQL(
            'ALTER TABLE service_operationlog MODIFY COLUMN user_id BIGINT NULL',
            reverse_sql='ALTER TABLE service_operationlog MODIFY COLUMN user_id INT NULL'
        ),
        # 修复 Problem 表的外键列类型
        migrations.RunSQL(
            'ALTER TABLE service_problem MODIFY COLUMN handler_id BIGINT NULL',
            reverse_sql='ALTER TABLE service_problem MODIFY COLUMN handler_id INT NULL'
        ),
        # 修复 Project 表的外键列类型
        migrations.RunSQL(
            'ALTER TABLE service_project MODIFY COLUMN project_manager_id BIGINT NULL',
            reverse_sql='ALTER TABLE service_project MODIFY COLUMN project_manager_id INT NULL'
        ),
        migrations.RunSQL(
            'ALTER TABLE service_project MODIFY COLUMN technical_manager_id BIGINT NULL',
            reverse_sql='ALTER TABLE service_project MODIFY COLUMN technical_manager_id INT NULL'
        ),
        # 修复 File 表的外键列类型
        migrations.RunSQL(
            'ALTER TABLE service_file MODIFY COLUMN uploader_id BIGINT NULL',
            reverse_sql='ALTER TABLE service_file MODIFY COLUMN uploader_id INT NULL'
        ),
    ]
