# Generated by Django 6.0.3 on 2026-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='occurrence_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_reason',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='reason_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solve_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
        migrations.AddField(
            model_name='problem',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关单时间'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_closed',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], default='no', max_length=20, verbose_name='是否关单'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('process', '流程问题'), ('software', '软件问题'), ('install', '安装部署'), ('complaint', '投诉')], default='process', max_length=20, verbose_name='问题类型'),
        ),
        migrations.AddField(
            model_name='problem',
            name='service_mode',
            field=models.CharField(choices=[('remote', '远程'), ('onsite', '现场')], default='remote', max_length=20, verbose_name='服务模式'),
        ),
    ]
