# Generated by Django 6.0.1 on 2026-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20260324_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_solved',
            field=models.CharField(blank=True, choices=[('yes', '是'), ('no', '否')], max_length=10, verbose_name='问题是否解决'),
        ),
        migrations.AddField(
            model_name='problem',
            name='man_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='人天'),
        ),
        migrations.AddField(
            model_name='problem',
            name='occurrence_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出现时间'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_reason',
            field=models.TextField(blank=True, verbose_name='问题原因'),
        ),
        migrations.AddField(
            model_name='problem',
            name='reason_type',
            field=models.CharField(blank=True, choices=[('bug', '缺陷bug'), ('env', '客户环境问题'), ('process', '流程问题'), ('consult', '客户咨询')], max_length=20, verbose_name='原因分类'),
        ),
        migrations.AddField(
            model_name='problem',
            name='screenshot',
            field=models.CharField(blank=True, max_length=500, verbose_name='问题截图'),
        ),
        migrations.AddField(
            model_name='problem',
            name='solve_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
    ]
