# Generated by Django 6.0.3 on 2026-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_problem_occurrence_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
