# Generated by Django 6.0.1 on 2026-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_problem_is_solved_problem_man_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='screenshot',
            field=models.FileField(blank=True, upload_to='problem_screenshots/', verbose_name='问题截图'),
        ),
    ]
