# Generated by Django 6.0.3 on 2026-04-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_customer_name_alter_problem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='man_days',
        ),
    ]
