# Generated by Django 6.0.3 on 2026-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_problem_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='screenshot',
            field=models.FileField(blank=True, upload_to='image', verbose_name='问题截图'),
        ),
    ]
