# Generated by Django 6.0.3 on 2026-04-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_problem_man_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.CharField(max_length=100, unique=True, verbose_name='商机编号')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '无效'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='service.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '商机编号',
                'verbose_name_plural': '商机编号列表',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='service_opp_custome_4a131a_idx'), models.Index(fields=['opportunity_number'], name='service_opp_opportu_cd8956_idx')],
            },
        ),
    ]
