# Generated by Django 6.0.3 on 2026-03-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_problem_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='handle_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_solved',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='source_customer_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='submit_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='submitter',
        ),
    ]
