# Generated by Django 6.0.3 on 2026-04-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, verbose_name='详情'),
        ),
    ]
