# Generated by Django 6.0.3 on 2026-03-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_problem_handle_time_remove_problem_is_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], max_length=20, verbose_name='当前状态'),
        ),
    ]
