# Generated by Django 6.0.3 on 2026-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='客户级别'),
        ),
        migrations.AddField(
            model_name='customer',
            name='opportunity_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='商机编号'),
        ),
    ]
