# Generated by Django 6.0.3 on 2026-04-20 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_opportunity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.opportunity', verbose_name='商机编号'),
        ),
    ]
