# Generated by Django 6.0.3 on 2026-04-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_problem_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='opportunity_number',
        ),
    ]
