# Generated by Django 6.0.3 on 2026-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_customer_customer_level_customer_opportunity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('lost', '流失')], max_length=20, verbose_name='当前状态'),
        ),
    ]
