# Generated by Django 6.0.3 on 2026-04-20 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_customer_opportunity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sales', to=settings.AUTH_USER_MODEL, verbose_name='销售负责人'),
        ),
    ]
