# Generated by Django 6.0.3 on 2026-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_customer_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sales_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='销售负责人'),
        ),
    ]
